### ISSUE TITLE
Missing: `dev` script in package.json

### ISSUE THREAD

**Issue by matb33** [gradealabs/generator-feathers#16]
In order to complement this commit (https://github.com/gradealabs/generator-feathers/commit/dd4ecb17009b46d929dacd47b712286c381f50c6), we should add a `dev` in `scripts` of `package.json` (I think it was just forgotten accidentally)

Based on a previous project in combination with the `if` statement highlighted in the following issue report, https://github.com/gradealabs/bullseye/issues/1, I suggest adding this:

```
"dev": "NODE_ENV=development node --require ts-node/register ./scripts/dev-server",
```

**Comment by matb33** [comment]
Alternatively, we could do what we typically do elsewhere in our code and get NODE_ENV with a fallback to 'development'.

e.g.:
```
const prestart = () => {
  // Handle interupt signal and PM2 graceful shutdown. This only necessary
  // while running the app in development.
  const env = process.env.NODE_ENV || 'development'
  if (env === 'development') {
```

**Comment by dschnare** [comment]
Opted to explicitly set `NODE_ENV=development` in the `dev` npm-script.
